# Generated by Django 4.1.3 on 2022-11-23 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
                ('arrival_date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('manufacture_date', models.DateField(default=datetime.datetime.today)),
                ('time', models.TimeField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_date', models.DateField(default=datetime.datetime.today)),
                ('needs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.products')),
            ],
        ),
    ]
